source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AppUnderControl-Bridge_Example', :exclusive => true do
  pod "AppUnderControl-Bridge", :path => "../"
end

target 'AppUnderControl-Bridge_Tests', :exclusive => true do
  pod "AppUnderControl-Bridge", :path => "../"

  
end
