source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'AppUnderControl-Bridge_Example', :exclusive => true do
  pod "AppUnderControl-Bridge", :path => "../"
end

target 'AppUnderControl-Bridge_Tests', :exclusive => true do
  pod "AppUnderControl-Bridge", :path => "../"
end